name: test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python test dependencies in a venv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install --progress-bar=off pytest

      - name: Install diff-pdf
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libpoppler-glib-dev \
            libwxgtk3.2-dev

          git clone https://github.com/vslavik/diff-pdf.git
          # v0.5.1
          cd diff-pdf && git checkout 150de72f7eebf8c9d69ee79b3cd28d9e7d7793f5
          ./bootstrap
          ./configure
          make
          sudo mv diff-pdf /usr/bin/diff-pdf

      - name: Docker build
        run: |
          docker build -t docker-onecodex-notebook .

      - name: Run lint checks & tests
        run: |
          sudo chmod 777 -R .
          . venv/bin/activate
          py.test -vv test/

      - name: Upload Report PDFs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: example reports
          path: |
            test/notebooks/diff.pdf
            test/notebooks/example.pdf
